version: '3.3'

services:

    umbook-graphdb:
        build: ./ontologia
        container_name: umbook-graphdb
        image: bragamann/umbook-graphdb:2020-07-03
        ports: 
            - "7200:7200"
        networks: 
            - graphdb
        volumes: 
            - graphdbvol:/opt/graphdb/home

    umbook-interfaceapp:
        build: ./interfaceapp
        depends_on: 
            - "umbook-apilayer"
            - "umbook-auth"
        container_name: umbook-interfaceapp
        image: bragamann/umbook-interfaceapp:2020-07-03
        ports: 
            - "8080:8080"
        networks: 
            - frontend

    umbook-apichat:
        build: ./apiChat
        depends_on: 
            - "umbook-mongo"
        container_name: umbook-apichat
        image: bragamann/umbook-apichat:2020-07-03
        ports: 
            - "3051:3051"
        networks: 
            - mongo
            - backend

    umbook-auth:
        build: ./authServer
        depends_on: 
            - "umbook-mongoauth"
            - "umbook-apidados"
        container_name: umbook-auth
        image: bragamann/umbook-auth:2020-07-03
        ports: 
            - "5000:5000"
        networks: 
            - mongoauth
            - frontend
            - backend

    umbook-apidados:
        build: ./apiDados
        container_name: umbook-apidados
        image: bragamann/umbook-apidados:2020-07-03
        ports:
            - "3050:3050"
        networks: 
            - backend
            - graphdb
        volumes:
            - ./ficheiros:/app/ficheiros


    umbook-apilayer:
        build: ./apiLayer
        depends_on: 
            - "umbook-apichat"
            - "umbook-apidados"
        container_name: umbook-apilayer
        image: bragamann/umbook-apilayer:2020-07-03
        ports:
          - "3049:3049"
        networks: 
          - frontend
          - backend
        volumes:
            - ./userimages:/app/public/images
        
  
    umbook-mongo:
        build: ./UMbookMongo
        image: bragamann/umbook-mongo:2020-07-03
        container_name: umbook-mongo
        ports:
            - "27017:27017"
        networks:
            - mongo
        volumes: 
            - mongodbvol:/data/db
            - ./umbook.sh:/docker-entrypoint-initdb.d/umbook.sh

    umbook-mongoauth:
        build: ./UMbookAuthMongo
        image: bragamann/umbook-mongoauth:2020-07-03
        container_name: umbook-mongoauth
        command: mongod --port 27018
        ports:
            - "27018:27018"
        networks:
            - mongoauth
            - backend
        volumes: 
            - mongodbauthvol:/data/db

    umbook-nginx:
        build: ./UMbookNGINX
        depends_on: 
            - "umbook-interfaceapp"
            - "umbook-apidados"
            - "umbook-apilayer"
            - "umbook-auth"
        image: bragamann/umbook-nginx:2020-07-03
        container_name: umbook-nginx
        ports:
            - "40005:40005"
        networks:
            - backend
            - frontend
       


networks:
    frontend:
    mongo:
    mongoauth:
    backend:
    graphdb:

volumes:
    graphdbvol:
    mongodbvol:
    mongodbauthvol: